using System.Text;
using Simploy.Shared.Contracts;

namespace Simploy.Agent;

/// <summary>
/// Renders the artifacts a deploy needs from the typed control-plane payload:
/// a .env file, a docker-compose.yml, and optionally a Caddyfile for
/// domain routing / weighted canary. Real apps that ship their own
/// docker-compose.yml are used as-is; a minimal one is generated as a fallback.
/// </summary>
public static class ComposeRenderer
{
    public static string Sanitize(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
            sb.Append(char.IsLetterOrDigit(c) || c is '-' or '_' or '.' ? c : '-');
        return sb.ToString();
    }

    public static string ServiceName(string slug) => Sanitize(slug);

    /// <summary>Removes host 'ports:' mappings (block form) from a compose so apps routed
    /// through the shared proxy don't bind a fixed host port (allows multi-env per VM).</summary>
    public static string StripHostPorts(string composeContent)
    {
        var lines = composeContent.Split('\n');
        var sb = new StringBuilder();
        var inPorts = false;
        foreach (var raw in lines)
        {
            var indent = raw.Length - raw.TrimStart().Length;
            var t = raw.Trim();
            if (t == "ports:" && indent >= 4) { inPorts = true; continue; }
            if (inPorts)
            {
                // Skip port mapping entries (dash-lists) until we leave the block.
                if (indent > 2 && (t.StartsWith("-") || t.StartsWith("host:") || t.StartsWith("target:") || t.StartsWith("published:") || t.StartsWith("protocol:"))) continue;
                if (indent <= 2) inPorts = false; // left the ports block
                else continue;
            }
            sb.AppendLine(raw);
        }
        return sb.ToString();
    }

    public static string RenderEnv(IReadOnlyDictionary<string, string>? env)
    {
        if (env is null || env.Count == 0) return "# Generated by Simploy\n";
        var sb = new StringBuilder("# Generated by Simploy\n");
        foreach (var (k, v) in env.OrderBy(x => x.Key, StringComparer.Ordinal))
            sb.Append($"{k}={v.Replace("\n", "\\n")}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a single-service compose that runs the built/tagged image. Used
    /// when the app doesn't ship its own docker-compose.yml.
    /// </summary>
    public static string RenderCompose(AgentDeployRequest req, string serviceName, int hostPort)
    {
        var sb = new StringBuilder();
        sb.AppendLine("services:");
        sb.AppendLine($"  {serviceName}:");
        sb.AppendLine($"    image: \"{req.ImageRepository}:{req.ImageTag}\"");
        sb.AppendLine("    env_file: .env");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    deploy:");
        sb.AppendLine("      resources:");
        sb.AppendLine("        limits:");
        sb.AppendLine("          memory: 512M");
        sb.AppendLine("    logging:");
        sb.AppendLine("      driver: json-file");
        sb.AppendLine("      options:");
        sb.AppendLine("        max-size: \"10m\"");
        sb.AppendLine("        max-file: \"3\"");
        RegisterService(sb, serviceName, hostPort, "simploy-proxy");
        sb.AppendLine("networks:");
        sb.AppendLine("  simploy-proxy:");
        sb.AppendLine("    external: true");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a blue/green pair of services for canary (new + old), both on a
    /// shared network so Caddy can weight between them.
    /// </summary>
    public static string RenderCanaryCompose(AgentDeployRequest req, string serviceName, int hostPort, string image, string oldImage)
    {
        var sb = new StringBuilder();
        sb.AppendLine("services:");
        sb.AppendLine($"  {serviceName}-new:");
        sb.AppendLine($"    image: \"{image}\"");
        sb.AppendLine("    env_file: .env");
        sb.AppendLine("    restart: unless-stopped");
        RegisterService(sb, $"{serviceName}-new", hostPort, "simploy-proxy");
        sb.AppendLine($"  {serviceName}-old:");
        sb.AppendLine($"    image: \"{oldImage}\"");
        sb.AppendLine("    env_file: .env");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    profiles: [\"old\"]");
        RegisterService(sb, $"{serviceName}-old", hostPort, "simploy-proxy");
        sb.AppendLine("networks:");
        sb.AppendLine("  simploy-proxy:");
        sb.AppendLine("    external: true");
        return sb.ToString();
    }

    private static void RegisterService(StringBuilder sb, string name, int hostPort, string network)
    {
        // No host port is published (routing is via the shared proxy), and no in-container
        // healthcheck is required (the agent gates on the container's Docker health/status).
        sb.AppendLine("    labels:");
        sb.AppendLine($"      simploy.project: \"{Sanitize(name)}\"");
        sb.AppendLine($"    networks:");
        sb.AppendLine($"      - {network}");
    }

    /// <summary>
    /// Renders a Caddyfile routing each domain to the service. Supports a
    /// weighted split between the current ("-new") and previous ("-old")
    /// service when a Canary deployment with a PreviousImageTag is in progress.
    /// </summary>
    public static string RenderCaddyfile(AgentDeployRequest req, string serviceName, int port)
    {
        if (req.Domains is null || req.Domains.Count == 0)
            return "# No domains configured - no Caddyfile generated\n";

        var newTarget = $"{serviceName}:{port}";
        var isCanary = req.Strategy.Equals("Canary", StringComparison.OrdinalIgnoreCase)
                       && req.CanaryPercent > 0
                       && !string.IsNullOrEmpty(req.PreviousImageTag);

        var sb = new StringBuilder();
        foreach (var d in req.Domains)
        {
            if (d.IsStatic || string.IsNullOrWhiteSpace(d.Host)) continue;

            sb.AppendLine($"# {d.Host}");
            // https => Caddy automatic HTTPS (Let's Encrypt). Requires the domain
            // to resolve to this server and ports 80/443 open. Otherwise http://.
            sb.AppendLine(d.EnableHttps ? $"{d.Host} {{" : $"http://{d.Host} {{");

            if (isCanary)
            {
                var oldTarget = $"{serviceName}-old:{port}";
                var weight = Math.Clamp(d.Weight > 0 ? d.Weight : req.CanaryPercent, 0, 100);
                sb.AppendLine($"    handle {weight}% {{");
                sb.AppendLine($"        reverse_proxy {newTarget}");
                sb.AppendLine("    }");
                sb.AppendLine($"    handle {100 - weight}% {{");
                sb.AppendLine($"        reverse_proxy {oldTarget}");
                sb.AppendLine("    }");
            }
            else
            {
                if (d.TargetService is not null)
                    sb.AppendLine($"    reverse_proxy {d.TargetService}");
                else
                    sb.AppendLine($"    reverse_proxy {newTarget}");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }
}
